name: sku02428flutter
description: Flutter client for sku02428 temporary realtime chat.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.1
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  file_picker: ^8.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
